version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 1
    schedule: 
      interval: "weekly"
    # Add assignees, reviewers
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
